### ISSUE TITLE
sa-logic container uses python 2 instead of 3

### ISSUE THREAD

**Issue by acbramley** [rinormaloku/k8s-mastery#1]
This morning I found your tutorial and noticed an issue with my app at the containerised level. The problem is that ubuntu seems to install python 2 by default and we need python 3.

**Comment by laszloatoth** [comment]
Hi rinormaloku,
Let me ask you about an interesting problem. I have started to clone your k8s-mastery project from the Github. 
My preliminary problem that I don't know what is the appropriate syntax here:
Navigate in the Terminal to the directory sa-logic/sa (repo) and type the following **command**:

python -m pip install -r requirements.txt
python -m textblob.download_corpora

My guess is that, we have a "&" between the commands. Am I right?

Actually I am on at the Python app running. So when I start the app, the following error messages referring to python2 environment. But I have both Python 2 & 3.
![image](https://user-images.githubusercontent.com/60490572/82762792-59fc0300-9e03-11ea-928f-e930cf553e6c.png)

![image](https://user-images.githubusercontent.com/60490572/82762810-6e400000-9e03-11ea-937c-a71b9186d224.png)

My question is that what version of Python was used originally? How you are referring to the Python version? How can I taylor my Python environment to see the complete app works? Thank you for your answer & patience.
BR,
  Laci.
