### ISSUE TITLE
docker build doesn't work

### ISSUE THREAD

**Issue by Narragansett** [rinormaloku/k8s-mastery#17]
Windows and Mac both give the same error, how to fix this??
Step 2/2 : COPY build /usr/share/nginx/html
COPY failed: stat /var/lib/docker/tmp/docker-builder802860079/build: no such file or directory

**Comment by xurongyang** [comment]
You need to run 'npm run build' first.

**Comment by rinormaloku** [comment]
Thanks @xurongyang!
